"""empty message

Revision ID: 1a7c74b6da09
Revises: 6663fdc07e3e
Create Date: 2021-11-30 13:41:41.583552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7c74b6da09'
down_revision = '6663fdc07e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('students_id', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'orders', 'students', ['students_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'students_id')
    # ### end Alembic commands ###
