"""empty message

Revision ID: 35914c705675
Revises: 4e429f0ff6a5
Create Date: 2021-10-11 23:01:42.310642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35914c705675'
down_revision = '4e429f0ff6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miss_person', sa.Column('miss_sex', sa.String(length=1), nullable=False))
    op.add_column('miss_person', sa.Column('phone', sa.String(length=11), nullable=False))
    op.add_column('miss_person', sa.Column('other_phone', sa.String(length=11), nullable=True))
    op.add_column('miss_person', sa.Column('miss_info', sa.TEXT(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miss_person', 'miss_info')
    op.drop_column('miss_person', 'other_phone')
    op.drop_column('miss_person', 'phone')
    op.drop_column('miss_person', 'miss_sex')
    # ### end Alembic commands ###
