"""empty message

Revision ID: 4814ccb795ad
Revises: 6c8b53cd672b
Create Date: 2021-11-28 17:13:16.038514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4814ccb795ad'
down_revision = '6c8b53cd672b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('application', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'application')
    # ### end Alembic commands ###
