"""empty message

Revision ID: 4e429f0ff6a5
Revises: 0136513bbc8d
Create Date: 2021-10-11 22:55:28.664189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e429f0ff6a5'
down_revision = '0136513bbc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miss_person',
    sa.Column('id', sa.String(length=18), nullable=False),
    sa.Column('miss_name', sa.String(length=10), nullable=False),
    sa.Column('miss_reason', sa.String(length=50), nullable=False),
    sa.Column('miss_place', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('users', sa.Column('phone', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_table('miss_person')
    # ### end Alembic commands ###
