"""empty message

Revision ID: 4e795598fe95
Revises: c4cba5d35043
Create Date: 2021-10-17 21:08:08.622861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e795598fe95'
down_revision = 'c4cba5d35043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('title', sa.String(length=20), nullable=False))
    op.add_column('notice', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_column('notice', 'notice_content')
    op.drop_column('notice', 'notice_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('notice_title', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('notice', sa.Column('notice_content', mysql.TEXT(), nullable=False))
    op.drop_column('notice', 'content')
    op.drop_column('notice', 'title')
    # ### end Alembic commands ###
