"""empty message

Revision ID: 622213abcd3e
Revises: f154bcc2dbfb
Create Date: 2021-11-30 16:26:58.502221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622213abcd3e'
down_revision = 'f154bcc2dbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('hash_password', sa.String(length=120), nullable=False))
    op.add_column('students', sa.Column('hash_password', sa.String(length=120), nullable=False))
    op.add_column('worker', sa.Column('hash_password', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'hash_password')
    op.drop_column('students', 'hash_password')
    op.drop_column('manager', 'hash_password')
    # ### end Alembic commands ###
