"""empty message

Revision ID: 6663fdc07e3e
Revises: 6c67484cc18f
Create Date: 2021-11-30 13:24:41.568697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6663fdc07e3e'
down_revision = '6c67484cc18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'students_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('students_id', mysql.VARCHAR(length=8), nullable=True))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'students', ['students_id'], ['id'])
    # ### end Alembic commands ###
