"""empty message

Revision ID: 6c8b53cd672b
Revises: c9ffdb20ffa0
Create Date: 2021-11-27 14:37:48.998125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8b53cd672b'
down_revision = 'c9ffdb20ffa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notify', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notify', 'datetime')
    # ### end Alembic commands ###
