"""empty message

Revision ID: bdb81dbfaeae
Revises: e807ed32cfe8
Create Date: 2021-11-01 13:34:35.193897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdb81dbfaeae'
down_revision = 'e807ed32cfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notify', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.add_column('students', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'datetime')
    op.alter_column('notify', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
