"""empty message

Revision ID: d9ccde06e425
Revises: 622213abcd3e
Create Date: 2021-11-30 16:37:00.247746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9ccde06e425'
down_revision = '622213abcd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'hash_password')
    op.drop_column('students', 'hash_password')
    op.drop_column('worker', 'hash_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('hash_password', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('students', sa.Column('hash_password', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('manager', sa.Column('hash_password', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
