"""empty message

Revision ID: f154bcc2dbfb
Revises: 1a7c74b6da09
Create Date: 2021-11-30 13:43:32.457730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f154bcc2dbfb'
down_revision = '1a7c74b6da09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'students_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('students_id', mysql.VARCHAR(length=8), nullable=True))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'students', ['students_id'], ['id'])
    # ### end Alembic commands ###
