"""empty message

Revision ID: f92126c38ede
Revises: 35914c705675
Create Date: 2021-10-11 23:07:46.051074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92126c38ede'
down_revision = '35914c705675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_area', sa.String(length=20), nullable=False),
    sa.Column('news_title', sa.String(length=20), nullable=False),
    sa.Column('news_main', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
