"""empty message

Revision ID: fd2f8b6c428c
Revises: 195d3ebf4f97
Create Date: 2021-10-17 10:47:12.824118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2f8b6c428c'
down_revision = '195d3ebf4f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('isdelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'isdelete')
    # ### end Alembic commands ###
